[env:esp32-s3-chassis]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Target board is the ESP32-S3 N16R8: 16 MB flash, 8 MB octal PSRAM.
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

build_src_filter =
  +<main.cpp>

[env:esp32-s3-chassis-first-flash]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Target board is the ESP32-S3 N16R8: 16 MB flash, 8 MB octal PSRAM.
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

build_src_filter =
  +<first_flash.cpp>

[env:esp32-s3-chassis-ota]
extends = env:esp32-s3-chassis
upload_protocol = espota
upload_port = esp32-chassis.local
