[platformio]
default_envs = esp32-s3-face-brain

[env:esp32-s3-face-brain]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Waveshare ESP32-S3-Touch-LCD-2 style board: N16R8, native USB.
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  moononournation/GFX Library for Arduino@1.4.7
  https://github.com/LiquidCGS/FastIMU.git

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM

[env:esp32-s3-face-brain-ota]
extends = env:esp32-s3-face-brain
upload_protocol = espota
upload_port = esp32-face.local
