[platformio]
default_envs = timer-cam

[env:timer-cam]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.flash_mode = dio
build_flags =
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue

[env:timer-cam-ota]
extends = env:timer-cam
upload_protocol = espota
upload_port = esp32-cam.local
