from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "config" / "face" / "robot-790-face.json"
OUT_DIR = ROOT / "config" / "face" / "generated"
POSE_FIELDS = ["open", "width", "curve", "skew", "teeth", "tension", "slant", "upperLift"]


def load_spec() -> dict[str, Any]:
    with SPEC_PATH.open("r", encoding="utf-8") as handle:
        spec = json.load(handle)
    validate_spec(spec)
    return spec


def validate_spec(spec: dict[str, Any]) -> None:
    mouth = spec["mouth"]
    if mouth["poseFields"] != POSE_FIELDS:
        raise ValueError(f"mouth.poseFields must be {POSE_FIELDS!r}")

    shape_order = mouth["shapeOrder"]
    shapes = mouth["shapes"]
    missing = [shape for shape in shape_order if shape not in shapes]
    extra = [shape for shape in shapes if shape not in shape_order]
    if missing or extra:
        raise ValueError(f"shapeOrder mismatch; missing={missing!r}, extra={extra!r}")

    seen_names: set[str] = set()
    for shape in shape_order:
        item = shapes[shape]
        names = [shape, *item.get("aliases", [])]
        for name in names:
            clean = str(name).lower()
            if clean in seen_names:
                raise ValueError(f"duplicate mouth shape or alias: {name}")
            seen_names.add(clean)
        pose = item["pose"]
        if set(pose) != set(POSE_FIELDS):
            raise ValueError(f"{shape} pose fields must be {POSE_FIELDS!r}")
        if not item.get("cppName"):
            raise ValueError(f"{shape} needs cppName")

    for mood, shape in mouth["moodMap"].items():
        if shape not in shapes:
            raise ValueError(f"mood {mood!r} maps to unknown mouth shape {shape!r}")


def float_js(value: float | int) -> str:
    return f"{float(value):.2f}".rstrip("0").rstrip(".")


def float_cpp(value: float | int) -> str:
    return f"{float(value):.2f}f"


def render_js(spec: dict[str, Any]) -> str:
    mouth = spec["mouth"]
    shapes = mouth["shapes"]
    ordered = mouth["shapeOrder"]
    mood_map = mouth["moodMap"]
    lines = [
        "// Generated by scripts/generate_face_contract.py from config/face/robot-790-face.json.",
        "// Do not edit by hand.",
        f"export const mouthShapes = {json.dumps(ordered)};",
        "",
        "export const mouthPoses = {",
    ]
    for shape in ordered:
        pose = shapes[shape]["pose"]
        values = ", ".join(f"{field}: {float_js(pose[field])}" for field in POSE_FIELDS)
        lines.append(f"  {json.dumps(shape)}: {{ {values} }},")
    lines.extend(
        [
            "};",
            "",
            f"export const mouthMoodMap = {json.dumps(mood_map, indent=2, sort_keys=True)};",
            "",
            "export function mouthShapeForMood(mood) {",
            "  return mouthMoodMap[mood] || \"neutral\";",
            "}",
            "",
            "export function mouthPoseFor(shape) {",
            "  return mouthPoses[shape] || mouthPoses.neutral;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def render_cpp(spec: dict[str, Any]) -> str:
    mouth = spec["mouth"]
    shapes = mouth["shapes"]
    ordered = mouth["shapeOrder"]
    mood_map = mouth["moodMap"]
    lines = [
        "// Generated by scripts/generate_face_contract.py from config/face/robot-790-face.json.",
        "// Do not edit by hand.",
        "#pragma once",
        "",
        "// Enum entries, in canonical order:",
    ]
    for shape in ordered:
        lines.append(f"//   {shapes[shape]['cppName']} -> {shape}")

    lines.extend(["", "// mouthShapeName switch cases:"])
    for shape in ordered:
        if shape == "neutral":
            continue
        lines.append(f'//   case MouthShape::{shapes[shape]["cppName"]}: return "{shape}";')

    lines.extend(["", "// parseMouthShapeName aliases:"])
    for shape in ordered:
        names = [shape, *shapes[shape].get("aliases", [])]
        checks = " || ".join(f'equalsIgnoreCase(text, "{name}")' for name in names)
        lines.append(f"//   {checks} -> MouthShape::{shapes[shape]['cppName']}")

    lines.extend(["", "// mouthPoseFor switch cases:"])
    for shape in ordered:
        pose = shapes[shape]["pose"]
        values = ", ".join(float_cpp(pose[field]) for field in POSE_FIELDS)
        lines.append(f"//   case MouthShape::{shapes[shape]['cppName']}: return {{{values}}};")

    lines.extend(["", "// mouthShapeForMood map:"])
    for mood, shape in sorted(mood_map.items()):
        lines.append(f"//   {mood} -> MouthShape::{shapes[shape]['cppName']}")

    shape_names = ", ".join(json.dumps(shape) for shape in ordered)
    lines.extend(["", f"constexpr const char *ROBOT_790_MOUTH_SHAPES[] = {{{shape_names}}};", ""])
    return "\n".join(lines)


def render_markdown(spec: dict[str, Any]) -> str:
    mouth = spec["mouth"]
    shapes = mouth["shapes"]
    lines = [
        "# Robot 790 Face Contract",
        "",
        "This is the inspectable face contract used to keep browser and hardware embodiments from drifting.",
        "Renderers may draw differently, but they should share names, pose intent, aliases, and mood mappings.",
        "",
        "## Mouth Shapes",
        "",
        "| Shape | C++ | Aliases | Topology | Pose |",
        "| --- | --- | --- | --- | --- |",
    ]
    for shape in mouth["shapeOrder"]:
        item = shapes[shape]
        aliases = ", ".join(item.get("aliases", [])) or "-"
        pose = ", ".join(f"{field}={float_js(item['pose'][field])}" for field in POSE_FIELDS)
        lines.append(f"| `{shape}` | `{item['cppName']}` | {aliases} | `{item['topology']}` | {pose} |")

    lines.extend(["", "## Skins", ""])
    for name, skin in spec["skins"].items():
        inherited = f" inherits `{skin['inherits']}`" if "inherits" in skin else ""
        lines.append(f"- `{name}`{inherited}: {skin.get('description', '')}")
    lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, text: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Robot 790 face contract artifacts.")
    parser.add_argument("--check", action="store_true", help="Fail if generated artifacts are out of date.")
    args = parser.parse_args()

    spec = load_spec()
    outputs = {
        OUT_DIR / "mouth_contract.js": render_js(spec),
        OUT_DIR / "mouth_contract.hpp": render_cpp(spec),
        OUT_DIR / "mouth_contract.md": render_markdown(spec),
    }

    changed = []
    if args.check:
        for path, text in outputs.items():
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                changed.append(str(path.relative_to(ROOT)))
        if changed:
            print("Generated face contract files are out of date:")
            for item in changed:
                print(f"  {item}")
            return 1
        print("Face contract generated files are up to date.")
        return 0

    for path, text in outputs.items():
        if write_if_changed(path, text):
            changed.append(str(path.relative_to(ROOT)))
    if changed:
        print("Updated generated face contract files:")
        for item in changed:
            print(f"  {item}")
    else:
        print("Generated face contract files were already current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
