from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import subprocess

Import("env")


PROJECT_DIR = Path(env.subst("$PROJECT_DIR")).resolve()
REPO_ROOT = PROJECT_DIR.parent.parent
HEADER_PATH = PROJECT_DIR / "include" / "firmware_build.h"
VERSION = "0.3.0"
TARGET = "esp32-face"
FEATURES = [
    "state_stamp",
    "mouth_marquee_fit",
    "mouth_x_offset",
    "external_eyes",
    "mouth_display",
    "aux_display",
    "display_flip",
    "wifi_prefs",
    "browser_ota",
]


def git_text(*args: str, default: str = "unknown") -> str:
    try:
        completed = subprocess.run(
            ["git", "-C", str(REPO_ROOT), *args],
            check=True,
            capture_output=True,
            text=True,
        )
    except Exception:
        return default
    value = completed.stdout.strip()
    return value or default


def c_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


commit = git_text("rev-parse", "--short=12", "HEAD")
branch = git_text("branch", "--show-current")
dirty_status = git_text("status", "--short", default="")
dirty = "1" if dirty_status else "0"
built_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
features = ",".join(FEATURES)

content = f"""#pragma once

// Generated by scripts/build_stamp.py during PlatformIO builds.
#define ROBOT790_FIRMWARE_TARGET "{c_string(TARGET)}"
#define ROBOT790_FIRMWARE_VERSION "{c_string(VERSION)}"
#define ROBOT790_FIRMWARE_GIT_COMMIT "{c_string(commit)}"
#define ROBOT790_FIRMWARE_GIT_BRANCH "{c_string(branch)}"
#define ROBOT790_FIRMWARE_GIT_DIRTY {dirty}
#define ROBOT790_FIRMWARE_BUILT_AT "{c_string(built_at)}"
#define ROBOT790_FIRMWARE_FEATURES "{c_string(features)}"
"""

HEADER_PATH.parent.mkdir(parents=True, exist_ok=True)
HEADER_PATH.write_text(content, encoding="utf-8")
print(f"Robot 790 firmware stamp: {TARGET} {VERSION} {commit}{'-dirty' if dirty == '1' else ''} {built_at}")
